export const ERROR_CODES = {
    MISSING_FIELDS: 'MISSING_FIELDS',
    INVALID_EMAIL: 'INVALID_EMAIL_FORMAT',
    ACCOUNT_EXISTS: 'ACCOUNT_EXISTS',
    WEAK_PASSWORD: 'WEAK_PASSWORD',
    SERVER_ERROR: 'SERVER_ERROR'
} as const